name: Build and Release Kustomizegen

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        go_os: [linux, windows, darwin]
        go_arch: [amd64, arm64]
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Run unit tests
        run: go test -v ./test

      - name: Build Go binary ${{ matrix.go_os }} - ${{ matrix.go_arch }}
        run: GOOS=${{ matrix.go_os }} GOARCH=${{ matrix.go_arch }} go build -ldflags="-s -w -X main.version=$(git describe --tags --always)" -gcflags="all=-trimpath=${PWD}" -o kustomizegen

      - name: Compress binary
        run: tar czf kustomizegen_${{ matrix.go_os }}_${{ matrix.go_arch }}.tar.gz kustomizegen

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kustomizegen_${{ matrix.go_os }}_${{ matrix.go_arch }}.tar.gz
          path: kustomizegen_${{ matrix.go_os }}_${{ matrix.go_arch }}.tar.gz

      - name: Create release
        uses: josephrodriguez/swift-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          token: ${{ secrets.FINE_GRAINED_TOKEN }}
          asset_path: kustomizegen_${{ matrix.go_os }}_${{ matrix.go_arch }}.tar.gz
