name: Build

on:
  pull_request:
  push:
    branches:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run unit tests
        run: go test -v ./test

      - name: Build Go binary
        run: go build -o kustomizegen

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: kustomizegen
