name: Build and Release Kustomizegen

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Run unit tests
        run: go test -v ./test

      - name: Build for Ubuntu
        run: GOOS=linux GOARCH=amd64 go build -o kustomizegen_linux_amd64

      - name: Compress binary
        if: startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/main'
        run: tar czf kustomizegen_linux_amd64.tar.gz kustomizegen_linux_amd64

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload binary as asset
        if: startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kustomizegen_linux_amd64.tar.gz
          asset_name: kustomizegen_${{ github.ref }}_linux_amd64.tar.gz
          asset_content_type: application/gzip
