name: Build and Publish Package
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Go application
        run: |
          go build -o kustomizegen
          dpkg-deb --build kustomizegen
        env:
          CGO_ENABLED: 0

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Describe your release here
          draft: false
          prerelease: false

      - name: Upload Package
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kustomizegen_1.0_amd64.deb
          asset_name: kustomizegen_1.0_amd64.deb
          asset_content_type: application/x-deb